# Generated by Django 4.2.1 on 2023-05-16 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user_master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.IntegerField(auto_created=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("rolename", models.CharField(max_length=50)),
                ("createdby", models.CharField(max_length=50)),
                (
                    "jn_date",
                    models.DateField(blank=True, default="0000-00-00", null=True),
                ),
                (
                    "lv_date",
                    models.DateField(blank=True, default="0000-00-00", null=True),
                ),
                ("dob", models.DateField(blank=True, default="0000-00-00", null=True)),
                ("mail_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "external_mail",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "personal_mail",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("mail_indi", models.CharField(blank=True, max_length=50, null=True)),
                ("gndr", models.IntegerField(default=1)),
                ("crnt_sts", models.IntegerField(default=1)),
                ("mgr", models.IntegerField(blank=True, null=True)),
                ("blood_group", models.CharField(blank=True, max_length=10, null=True)),
                ("phno", models.IntegerField(blank=True, null=True)),
                ("loc", models.CharField(blank=True, max_length=50, null=True)),
                ("gl", models.CharField(blank=True, max_length=60, null=True)),
                ("tl", models.IntegerField(blank=True, null=True)),
                ("company_id", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=datetime.datetime.now)),
                ("delete1", models.IntegerField(default=0)),
                ("marital_status", models.IntegerField(default=0)),
                ("tms_status", models.IntegerField(default=0)),
                ("ass_role", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "qualification",
                    models.CharField(
                        blank=True, default="SSC", max_length=20, null=True
                    ),
                ),
                (
                    "marriage_date",
                    models.DateField(blank=True, default="0000-00-00", null=True),
                ),
            ],
        ),
    ]
