# Generated by Django 4.2.1 on 2023-05-16 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("master_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user_master",
            table="user_master",
        ),
    ]
