# Generated by Django 4.2.1 on 2023-05-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_app", "0002_alter_user_master_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_master",
            name="id",
        ),
        migrations.AlterField(
            model_name="user_master",
            name="userid",
            field=models.IntegerField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="userid",
            ),
        ),
    ]
