# Generated by Django 4.2.1 on 2023-05-17 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("master_app", "0003_remove_user_master_id_alter_user_master_userid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_master",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="user_master",
            name="jn_date",
        ),
        migrations.RemoveField(
            model_name="user_master",
            name="lv_date",
        ),
        migrations.RemoveField(
            model_name="user_master",
            name="marriage_date",
        ),
    ]
